dev:
	docker buildx build -t rmedicharla/kubefs-auth:dev . && docker push rmedicharla/kubefs-auth:dev

prod:
	docker buildx build -t rmedicharla/kubefs-auth:prod . && docker push rmedicharla/kubefs-auth:prod
