develop:
	docker buildx build -t rmedicharla/kubefs-auth:latest . && docker push rmedicharla/kubefs-auth:latest

prod:
	docker buildx build -t rmedicharla/kubefs-auth:prod . && docker push rmedicharla/kubefs-auth:prod
