#!/bin/bash

default_helper() {
    TYPE=$1
    if [ $TYPE -eq 1 ]; then
        echo "$2 is not a valid argument, please follow types below"
    fi

    echo "
    kubefs - a cli tool to create & deploy full stack applications onto kubernetes clusters

    kubefs config - config login credentials & deployment targets to be used 
    kubefs create - easily create backend, frontend, & db constructs to be used within your application
    kubefs docker - create & test docker images for created resources to be deployed onto the clusters
    kubefs deploy - deploy the build targets onto the cluster!
    kubefs describe - describe the information about a construct
    kubefs init <project_name> - download all required dependencies & set up configuration files
    kubefs exec - execute components to test your code
    kubefs setup - setup kubefs for the first time
    "
}

main(){
    SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

    if [ -z "$1" ]; then
        default_helper 0
        return 0
    fi

    command=$1
    shift
    case $command in
        "config") source ${SCRIPT_DIR}/scripts/config.sh;;
        "create") source ${SCRIPT_DIR}/scripts/create.sh;;
        "deploy") source ${SCRIPT_DIR}/scripts/deploy.sh;;
        "describe") source ${SCRIPT_DIR}/scripts/describe.sh;;
        "docker") source ${SCRIPT_DIR}/scripts/docker.sh;;
        "exec") source ${SCRIPT_DIR}/scripts/exec.sh;;
        "init") source ${SCRIPT_DIR}/scripts/init.sh;;
        "setup") source $SCRIPT_DIR/scripts/setup.sh;;
        "--help") default_helper 0;;
        *) default_helper 1 $command;;
    esac
}

main $@
exit 0


