#!/bin/bash

default_helper() {
    TYPE=$1
    if [ $TYPE -eq 1 ]; then
        echo "$2 is not a valid argument, please follow types below"
    fi

    echo "
    kubefs - a cli tool to create & deploy full stack applications onto kubernetes clusters

    Usage: kubefs <OPTION>
        kubefs compile - build and push the docker images for resources
        kubefs config - configure the kubefs environment & set auth credentials
        kubefs create - easily create backend, frontend, & db constructs to be used within your application
        kubefs deploy - deploy the build targets onto the cluster!
        kubefs describe - describe the information about a construct
        kubefs execute - execute components locally to test your code
        kubefs execute-docker - execute resources as docker containers
        kubefs init - download all required dependencies & set up configuration files
        kubefs setup - setup kubefs for the first time
        kubefs undeploy - undeploy components from release
    "
}

source_scripts(){
    if [ -z $KUBEFS_CONFIG ]; then
        echo "Please run kubefs setup to configure your kubefs environment"
        return 1
    fi

    file_path=$1
    shift
    source $file_path
}

main(){
    
    if [ -z "$1" ]; then
        default_helper 0
        return 0
    fi

    OPTION=$1
    shift
    case $OPTION in
        "compile") source_scripts ${KUBEFS_CONFIG}/scripts/compile.sh $@;;
        "config") source_scripts ${KUBEFS_CONFIG}/scripts/config.sh $@;;
        "create") source_scripts ${KUBEFS_CONFIG}/scripts/create.sh $@;;
        "deploy") source_scripts ${KUBEFS_CONFIG}/scripts/deploy.sh $@;;
        "describe") source_scripts ${KUBEFS_CONFIG}/scripts/describe.sh $@;;
        "execute") source_scripts ${KUBEFS_CONFIG}/scripts/execute.sh $@;;
        "exec-docker") source_scripts ${KUBEFS_CONFIG}/scripts/exec-docker.sh $@;;
        "init") source_scripts ${KUBEFS_CONFIG}/scripts/init.sh $@;;
        "setup") source $KUBEFS_CONFIG/scripts/setup.sh;;
        "undeploy") source_scripts ${KUBEFS_CONFIG}/scripts/undeploy.sh $@;;
        "--help") default_helper 0;;
        *) default_helper 1 $OPTION;;
    esac
}

main $@
exit 0


