develop:
	docker buildx build -t rmedicharla/kubefs-api:latest . && docker push rmedicharla/kubefs-api:latest

prod:
	docker buildx build -t rmedicharla/kubefs-api:prod . && docker push rmedicharla/kubefs-api:prod
