dev:
	docker buildx build -t rmedicharla/kubefs-api:dev . && docker push rmedicharla/kubefs-api:dev

prod:
	docker buildx build -t rmedicharla/kubefs-api:prod . && docker push rmedicharla/kubefs-api:prod
